gcc-neon to 5.1.0-5

diff --git a/gcc-neon/PKGBUILD b/gcc-neon/PKGBUILD
--- a/gcc-neon/PKGBUILD
+++ b/gcc-neon/PKGBUILD
@@ -12,14 +12,16 @@
 #  - replaced bugurl with our GitHub issue page
 #  - patch to disable LDRD/STRD instructions on ARMv5
 
+#Modifier: gripped <forum.odroid.com> Build with NEON support for the XU3
+
 noautobuild=1
+
 pkgname=('gcc-neon' 'gcc-libs-neon' 'gcc-fortran-neon' 'gcc-objc-neon' 'gcc-go-neon')
-pkgver=4.9.2
-_pkgver=4.9
-_islver=0.12.2
-_cloogver=0.18.1
-pkgrel=4
-_snapshot=4.9-20150304
+pkgver=5.1.0
+_pkgver=5
+_islver=0.14.1
+pkgrel=5
+_snapshot=5-20150623
 pkgdesc="The GNU Compiler Collection"
 arch=('i686' 'x86_64')
 license=('GPL' 'LGPL' 'FDL' 'custom')
@@ -30,12 +32,18 @@ options=('!emptydirs' '!distcc')
 source=(#ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
         ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
         http://isl.gforge.inria.fr/isl-${_islver}.tar.bz2
-        http://www.bastoul.net/cloog/pages/download/cloog-${_cloogver}.tar.gz
-        0001-ARMv5-disable-LDRD-STRD.patch)
-md5sums=('863bb9d2a9551c9b7447cfc8b7cc7498'
-         'e039bfcfb6c2ab039b8ee69bf883e824'
-         'e34fca0540d840e5d0f6427e98c92252'
-         '924a9bcdd7852410667f04ce18c305d7')
+        pr65882.patch
+        pr66647.patch
+        pr66035.patch
+        0001-ARMv5-disable-LDRD-STRD.patch
+        march.patch)
+md5sums=('69432bf92cb6cdc8399c1bfc28c4f801'
+         '118d1a379abf7606a3334c98a8411c79'
+         'f64c1781d8bcac1ea168c2b7091ca2bd'
+         '720df658a726b6e0e541c58296bd5672'
+         '5b980076cd5fcbc3aff6014f306282dd'
+         '924a9bcdd7852410667f04ce18c305d7'
+         '332adb2bc0a80a29b8903e633cac5b06')
 
 if [ -n "${_snapshot}" ]; then
   _basedir=gcc-${_snapshot}
@@ -48,9 +56,8 @@ _libdir="usr/lib/gcc/$CHOST/$pkgver"
 prepare() {
   cd ${srcdir}/${_basedir}
 
-  # link isl/cloog for in-tree builds
+  # link isl for in-tree build
   ln -s ../isl-${_islver} isl
-  ln -s ../cloog-${_cloogver} cloog
 
   # Do not run fixincludes
   sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in
@@ -59,6 +66,18 @@ prepare() {
 
   # hack! - some configure tests for header files using "$CPP $CPPFLAGS"
   sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" {libiberty,gcc}/configure
+
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65882
+  patch -p0 -i ${srcdir}/pr65882.patch
+
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66647
+  patch -p0 -i ${srcdir}/pr66647.patch
+
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66035
+  patch -p1 -i ${srcdir}/pr66035.patch
+  
+  #libatomic adds -march=armv7-a which causes a warning when using -mcpu=cortex-a15.cortex-a7 and the build fails
+  patch -p0 -i ${srcdir}/march.patch
 
   # ALARM: Specify build host types, triplet patch
   [[ $CARCH == "arm" ]] && CONFIGFLAG="--host=armv5tel-unknown-linux-gnueabi --build=armv5tel-unknown-linux-gnueabi --with-arch=armv5te --with-float=soft"
@@ -85,20 +104,16 @@ build() {
       --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues \
       --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ \
       --enable-shared --enable-threads=posix \
-      --with-system-zlib --enable-__cxa_atexit \
+      --with-system-zlib --with-isl --enable-__cxa_atexit \
       --disable-libunwind-exceptions --enable-clocale=gnu \
       --disable-libstdcxx-pch --disable-libssp \
       --enable-gnu-unique-object --enable-linker-build-id \
-      --enable-cloog-backend=isl \
       --enable-lto --enable-plugin --enable-install-libiberty \
-      --with-linker-hash-style=gnu \
+      --with-linker-hash-style=gnu --enable-gnu-indirect-function \
       --disable-multilib --disable-werror \
-      --enable-checking=release $CONFIGFLAG
-
-# gcc-5.0 changes
-#      --with-default-libstdcxx-abi=c++98    - before gcc-5.0 c++ rebuild
-#      --enable-gnu-indirect-function
-#      --with-isl    - cloog no longer needed
+      --enable-checking=release \
+      --with-default-libstdcxx-abi=c++98 \
+      $CONFIGFLAG
 
   make
 
@@ -111,23 +126,22 @@ check() {
 
   # increase stack size to prevent test failures
   # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
-  #ulimit -s 32768
+  ulimit -s 32768
 
   # do not abort on error as some are "expected"
-  #make -k check || true
-  #${srcdir}/${_basedir}/contrib/test_summary
+  make -k check || true
+  ${srcdir}/${_basedir}/contrib/test_summary
 }
 
 package_gcc-libs-neon()
 {
   pkgdesc="Runtime libraries shipped by GCC"
   groups=('base')
-  depends=('glibc>=2.20')
+  depends=('glibc-neon>=2.21')
   options=('!emptydirs' '!strip')
   install=gcc-libs.install
   conflicts=('gcc-libs')
   provides=("gcc-libs=${pkgver}")
-
   cd ${srcdir}/gcc-build
 
   make -C $CHOST/libgcc DESTDIR=${pkgdir} install-shared
@@ -160,19 +174,18 @@ package_gcc-libs-neon()
 package_gcc-neon()
 {
   pkgdesc="The GNU Compiler Collection - C and C++ frontends"
-  depends=("gcc-libs=$pkgver-$pkgrel" 'binutils>=2.24' 'libmpc')
+  depends=("gcc-libs-neon=$pkgver-$pkgrel" 'binutils-neon>=2.25' 'libmpc')
   groups=('base-devel')
   options=('staticlibs')
   install=gcc.install
   conflicts=('gcc')
   provides=("gcc=${pkgver}")
-
   cd ${srcdir}/gcc-build
   
   make -C gcc DESTDIR=${pkgdir} install-driver install-cpp install-gcc-ar \
     c++.install-common install-headers install-plugin install-lto-wrapper
 
-  install -m755 gcc/gcov $pkgdir/usr/bin/
+  install -m755 -t $pkgdir/usr/bin/ gcc/gcov{,-tool}
   install -m755 -t $pkgdir/${_libdir}/ gcc/{cc1,cc1plus,collect2,lto1}
 
   make -C $CHOST/libgcc DESTDIR=${pkgdir} install
@@ -183,6 +196,7 @@ package_gcc-neon()
   make -C $CHOST/libstdc++-v3/libsupc++ DESTDIR=${pkgdir} install
   make -C $CHOST/libstdc++-v3/python DESTDIR=${pkgdir} install
 
+  make DESTDIR=${pkgdir} install-libcc1
   install -d $pkgdir/usr/share/gdb/auto-load/usr/lib
   mv $pkgdir/usr/lib/libstdc++.so.6.*-gdb.py \
     $pkgdir/usr/share/gdb/auto-load/usr/lib/
@@ -190,7 +204,11 @@ package_gcc-neon()
 
   make DESTDIR=${pkgdir} install-fixincludes
   make -C gcc DESTDIR=${pkgdir} install-mkheaders
+
   make -C lto-plugin DESTDIR=${pkgdir} install
+  install -dm755 ${pkgdir}/usr/lib/bfd-plugins/
+  ln -s /usr/lib/gcc/$CHOST/${pkgver}/liblto_plugin.so \
+    ${pkgdir}/usr/lib/bfd-plugins/
 
   make -C $CHOST/libgomp DESTDIR=${pkgdir} install-nodist_toolexeclibHEADERS \
     install-nodist_libsubincludeHEADERS
@@ -251,14 +269,15 @@ EOF
 package_gcc-fortran-neon()
 {
   pkgdesc="Fortran front-end for GCC"
-  depends=("gcc=$pkgver-$pkgrel")
+  depends=("gcc-neon=$pkgver-$pkgrel")
   options=('!emptydirs')
   install=gcc-fortran.install
   conflicts=('gcc-fortran')
   provides=("gcc-fortran=${pkgver}")
-
+ 
   cd ${srcdir}/gcc-build
-  make -C $CHOST/libgfortran DESTDIR=$pkgdir install-{{caf,my}execlibLTLIBRARIES,toolexeclibDATA}
+  make -C $CHOST/libgfortran DESTDIR=$pkgdir install-{caf,my}execlibLTLIBRARIES \
+    install-{toolexeclibDATA,nodist_fincludeHEADERS}
   make -C $CHOST/libgomp DESTDIR=$pkgdir install-nodist_fincludeHEADERS
   make -C gcc DESTDIR=$pkgdir fortran.install-{common,man,info}
   install -Dm755 gcc/f951 $pkgdir/${_libdir}/f951
@@ -273,7 +292,7 @@ package_gcc-fortran-neon()
 package_gcc-objc-neon()
 {
   pkgdesc="Objective-C front-end for GCC"
-  depends=("gcc=$pkgver-$pkgrel")
+  depends=("gcc-neon=$pkgver-$pkgrel")
   conflicts=('gcc-objc')
   provides=("gcc-objc=${pkgver}")
 
@@ -290,16 +309,18 @@ package_gcc-objc-neon()
 package_gcc-go-neon()
 {
   pkgdesc="Go front-end for GCC"
-  depends=("gcc=$pkgver-$pkgrel")
+  depends=("gcc-neon=$pkgver-$pkgrel")
   options=('!emptydirs')
   install=gcc-go.install
-  conflicts=('gcc-go')
+  conflicts=('gcc-go' 'go')
   provides=("gcc-go=${pkgver}")
 
   cd ${srcdir}/gcc-build
   make -C $CHOST/libgo DESTDIR=$pkgdir install-exec-am
   make -C gcc DESTDIR=$pkgdir go.install-{common,man,info}
   install -Dm755 gcc/go1 $pkgdir/${_libdir}/go1
+
+  make DESTDIR=${pkgdir} install-gotools
 
   # Install Runtime Library Exception
   install -d ${pkgdir}/usr/share/licenses/gcc-go/
